name: Main workflow

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # macOS does not have libpython at the moment:
          # https://github.com/actions/virtual-environments/issues/125
          # - macos-latest
          - windows-latest
        architecture: [x64, x86]
        python-version: ['3.7', '3.8']
        julia-version: ['1.3']
        exclude:
          - os: ubuntu-latest
            architecture: x86
      fail-fast: false
    name: ${{ matrix.os }} ${{ matrix.architecture }}
      Python ${{ matrix.python-version }}
      Julia ${{ matrix.julia-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.architecture }}
      - run: python src/julia/find_libpython.py --list-all --verbose
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: Install PyCall
        run: python ci/install_pycall.py
      - name: Run test
        run: python -m tox
        env:
          CI: 'true'  # run tests marked by @only_in_ci
          TOXENV: py
          PYJULIA_TEST_REBUILD: 'yes'
      - run: cat .tox/py/log/pytest.log
        if: always()
